# Generated by Django 4.1 on 2022-11-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='real_estate_agency',
            field=models.CharField(max_length=32),
        ),
    ]
